### ISSUE TITLE
[Umbrella Task] PowerShell Core Support

### ISSUE THREAD

**Issue by OCram85** [OCram85/PSCredentialStore#31]
## :notebook:  ToDo

- [x] Refactor the Module to Support PowerShell 6 Core
- [x] Add Travis build jobs for Linux & MacOS testing
- [x] Update the dev dependencies
  - [x] `Nuget`
  - [x] `Pester`
  - [x] `posh-git`
